// <auto-generated />
namespace MoreForLess.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IncreasedLengthNameGood : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncreasedLengthNameGood));
        
        string IMigrationMetadata.Id
        {
            get { return "201803051156210_IncreasedLengthNameGood"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
